project:
  type: website

website:
  title: "R useRs Group Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/thedbcooper/R-useRs-blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
